basePath: /
definitions:
  github_com_pixel365_messagio_internal_model.Creds:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  github_com_pixel365_messagio_internal_model.InncomingMessage:
    properties:
      text:
        type: string
      to:
        type: string
    required:
    - text
    - to
    type: object
  github_com_pixel365_messagio_internal_model.Message:
    properties:
      id:
        type: string
      status:
        $ref: '#/definitions/github_com_pixel365_messagio_internal_model.Status'
      text:
        type: string
      to:
        type: string
    required:
    - id
    - status
    - text
    - to
    type: object
  github_com_pixel365_messagio_internal_model.Status:
    enum:
    - pending
    - error
    - completed
    type: string
    x-enum-varnames:
    - Pending
    - Error
    - Completed
  github_com_pixel365_messagio_internal_model.Token:
    properties:
      access_token:
        type: string
      expires_at:
        type: string
      token_type:
        type: string
    required:
    - access_token
    - expires_at
    - token_type
    type: object
host: 62.109.20.78:8081
info:
  contact:
    email: pixel365.sup@gmail.com
    name: Ruslan Semagin
  description: Test API service
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Messagio API
  version: 1.0.1
paths:
  /api/batch:
    post:
      consumes:
      - application/json
      description: send multiple messages
      parameters:
      - default: Bearer XXX
        description: Your access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Messages
        in: body
        name: messages
        required: true
        schema:
          items:
            $ref: '#/definitions/github_com_pixel365_messagio_internal_model.InncomingMessage'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_pixel365_messagio_internal_model.Message'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "422":
          description: Unprocessable Entity
      summary: Multiple messages
  /api/details/{id}:
    get:
      consumes:
      - application/json
      description: send multiple messages
      parameters:
      - default: Bearer XXX
        description: Your access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Message ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_pixel365_messagio_internal_model.Message'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "422":
          description: Unprocessable Entity
      summary: Multiple messages
  /api/single:
    post:
      consumes:
      - application/json
      description: send single message
      parameters:
      - default: Bearer XXX
        description: Your access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Message object
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/github_com_pixel365_messagio_internal_model.InncomingMessage'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_pixel365_messagio_internal_model.Message'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "422":
          description: Unprocessable Entity
      summary: Single message
  /auth:
    post:
      consumes:
      - application/json
      description: get access token
      parameters:
      - description: Username (email) and password (min 6 characters)
        in: body
        name: creds
        required: true
        schema:
          $ref: '#/definitions/github_com_pixel365_messagio_internal_model.Creds'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_pixel365_messagio_internal_model.Token'
        "400":
          description: Bad Request
        "422":
          description: Unprocessable Entity
      summary: Authentication
swagger: "2.0"
